### ISSUE TITLE
Ability to read HTML from file and provide as argument for `tmpli html`

### ISSUE THREAD

**Issue by joemarct** [onionhammer/nim-templates#4]
I have tried to read a file and feed it to `tmpli html`, like this:
`tmpli html readFile "templates/base.html"`

However, I got this error:  `Error: field 'strVal' cannot be found`

**Comment by onionhammer** [comment]
This may be possible to implement with [staticRead](http://nim-lang.org/docs/system.html#staticRead,string); but i don't think it will work out of the box.

**Comment by joemarct** [comment]
I hacked my way to achieve my end goal, which is basically to write a separate HTML file and simply pass the path to `tmpli` as argument. I initiated a pull request, in case you would want to merge my revisions.

**Comment by joemarct** [comment]
Just to update on the progress of this issue: We ended up creating a separate macro `tmplf` for reading HTML code from file. This has been merged to master in 84db5ce164b3512a194c54d20510806b454958e8.
