### ISSUE TITLE
Support for JS target

### ISSUE THREAD

**Issue by honewatson** [onionhammer/nim-templates#7]
Hi there great work on this thanks,

Can you please provide support for the JS Target?

Compiler error is: OS module not ported to your operating system!

Then we have an isomorphic templating option.  Karax does not support native compiler.

**Comment by onionhammer** [comment]
@honewatson in theory nim-templates shouldn't rely on the `os` module. It looks like it was added somewhat [recently](https://github.com/onionhammer/nim-templates/commit/6682218ba874baa2160eb4d1168e306cee23b2bd#diff-a4d1909b4579c67f4ca4ae5f67156596). You should experiment with simply removing it and trying to use tmplf, I will happily review any changes you'd like to submit a PR for

**Comment by honewatson** [comment]
Ok thanks I will take a look.
